# Generated by Django 5.0.2 on 2024-02-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_application_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='unchecked', max_length=255),
        ),
    ]
